// <auto-generated />
namespace EmployeeManagerModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271247548_11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
